apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "backend.podAnnotations" . | nindent 8 }}
        {{- if and .Values.opentelemetry.enabled .Values.opentelemetry.instrumentation }}
        instrumentation.opentelemetry.io/inject-sdk: {{ .Values.opentelemetry.instrumentation }}
        {{- end }}
        {{- if .Values.app.db.secret.useSecretsManager }}
        reloader.stakater.com/auto: "true"
        {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: {{ include "backend.configMapName" . }}
            {{- if .Values.app.db.secret.useSecretsManager }}
            - secretRef:
                name: {{ .Values.app.db.secret.k8sSecretName }}
            {{- end }}
            - secretRef:
                name: {{ .Values.sharedSecretsRef }}
            {{- range .Values.app.extraSecretRefs }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.app.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.app.port }}
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            {{- if .Values.app.db.secret.useSecretsManager }}
            - name: aws-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
            {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        {{- if .Values.app.db.secret.useSecretsManager }}
        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "backend.fullname" . }}-db-secrets
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
