{{- if .Values.app.db.secret.useSecretsManager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "backend.fullname" . }}-db-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.app.db.secret.region | default "us-east-1" }}
    usePodIdentity: "true"
    objects: |
      - objectName: {{ .Values.app.db.secret.secretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - secretName: {{ .Values.app.db.secret.k8sSecretName }}
      type: Opaque
      data:
        - objectName: username
          key: SPRING_DATASOURCE_USERNAME
        - objectName: password
          key: SPRING_DATASOURCE_PASSWORD
{{- end }}
