# --------------------------------------------------------------------
# Konecta RDS Master Secret
# --------------------------------------------------------------------
# A single Terraform-managed secret holding the RDS *master* username/
# password used to create all 5 Konecta database instances (c7_03-c7_07).
# Mirrors how GleamGoods' gleamgoods-db-secret is used in
# 08_AWS_managed_databases: read only via a Terraform local for
# aws_db_instance's username/password - never opened as an independent
# connection, and never itself rotated.
#
# Unlike gleamgoods-db-secret (created out-of-band, only ever read via a
# `data` source), Konecta explicitly wants no manual secret-creation step
# for this one - so both the secret container and its value are Terraform
# resources here, not data sources. This is safe specifically because
# this secret is never rotated: nothing outside Terraform ever changes
# its value, so there's no drift for Terraform to fight over.
#
# This is NOT what Konecta services read at runtime - see c9_02 for the
# per-service app-user secrets (one per database, auto-rotated) that
# actually get mounted into pods (c8_01/c8_02).

# Password generated by Terraform - alphanumeric only (no special
# characters). Punctuation in a generated DB password has broken DSN/
# connection-string parsing in this project before (see the
# excludePunctuation gotcha in 08_AWS_managed_databases' rotation
# Lambdas) - avoiding it entirely here sidesteps that whole class of bug.
resource "random_password" "konecta_db_password" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "konecta_secret" {
  name        = var.konecta_db_secret_name
  description = "Konecta RDS master credentials - used only to set each aws_db_instance's master username/password, never mounted to application pods, never rotated"

  tags = {
    Name      = "${local.name}-db-secret"
    Component = "Konecta"
  }
}

resource "aws_secretsmanager_secret_version" "konecta_secret_value" {
  secret_id = aws_secretsmanager_secret.konecta_secret.id
  secret_string = jsonencode({
    username = var.konecta_db_username
    password = random_password.konecta_db_password.result
  })
}

locals {
  konecta_master_secret_json = jsondecode(aws_secretsmanager_secret_version.konecta_secret_value.secret_string)
}

output "konecta_db_secret_arn" {
  description = "ARN of the Konecta RDS master secret"
  value       = aws_secretsmanager_secret.konecta_secret.arn
}
