# --------------------------------------------------------------------
# Shared Konecta DB Secret
# --------------------------------------------------------------------
# A single AWS Secrets Manager secret, fully created and managed by
# Terraform, shared by every Konecta database and every Konecta service.
# Used here as the master username/password for each aws_db_instance
# below, and mounted into every Konecta service pod via the Secrets
# Store CSI Driver (see c8_01/c8_02).
#
# Unlike GleamGoods' gleamgoods-db-secret (created out-of-band, only
# ever read via a `data` source), Konecta explicitly wants no manual
# secret-creation step - so both the secret container and its value are
# resources here, not data sources.

# Password generated by Terraform - alphanumeric only (no special
# characters). Punctuation in a generated DB password has broken DSN/
# connection-string parsing in this project before (see the
# excludePunctuation gotcha in 08_AWS_managed_databases' rotation
# Lambdas) - avoiding it entirely here sidesteps that whole class of bug.
resource "random_password" "konecta_db_password" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "konecta_secret" {
  name        = var.konecta_db_secret_name
  description = "Shared master DB credentials for every Konecta RDS PostgreSQL database and service"

  tags = {
    Name      = "${local.name}-db-secret"
    Component = "Konecta"
  }
}

resource "aws_secretsmanager_secret_version" "konecta_secret_value" {
  secret_id = aws_secretsmanager_secret.konecta_secret.id
  secret_string = jsonencode({
    username = var.konecta_db_username
    password = random_password.konecta_db_password.result
  })
}

locals {
  konecta_secret_json = jsondecode(aws_secretsmanager_secret_version.konecta_secret_value.secret_string)
}

output "konecta_db_secret_arn" {
  description = "ARN of the shared Konecta DB secret"
  value       = aws_secretsmanager_secret.konecta_secret.arn
}
