apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: konecta
  labels:
    app.kubernetes.io/name: konecta-frontend
    app.kubernetes.io/instance: konecta-frontend
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: konecta
